apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdpservice-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pdpservice
  template:
    metadata:
      labels:
        app: pdpservice
    spec:
      containers:
      - name: pdpservice
        image: pavankumarsangisetti/pdpservice:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
